name: jd_automation
description: macOS JD Seller automatic customer-service assistant.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.3.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
